name: Bug Report
description: 버그 리포트
title: "[BUG]: "
labels: ["🐛 버그"]
body:
  - type: dropdown
    id: issueType
    attributes:
      label: 📥 Issue Type
      description: 'Jira 이슈 타입을 선택해주세요.'
      options:
        - Bug
        - Task
        - Story
      default: 0
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '📮 상세 내용 Description'
      description: '버그 내용을 상세히 적어주세요.'
      value: |
        ## 어떤 버그인가요?
        > 어떤 버그인지 간단하게 설명해주세요

        ## 어떤 상황에서 발생한 버그인가요?
        > 어떤 상황에서 / 무엇을 했을 때 / 어떻게 되어야 하는데 / 결과는 어떤지 서술해주세요

        ## 예상 결과
        > 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

        ## 참고 자료
    validations:
      required: true
