name: Custom Report
description: μ‘μ—… μ΄μ
title: "[TASK]: "
labels: []
body:
  - type: dropdown
    id: issueType
    attributes:
      label: π“¥ Issue Type
      description: 'Jira μ΄μ νƒ€μ…μ„ μ„ νƒν•΄μ£Όμ„Έμ”.'
      options:
        - Task
        - Story
        - Bug
      default: 0
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 'π“® μƒμ„Έ λ‚΄μ© Description'
      description: 'μ‘μ—… λ‚΄μ©μ„ μƒμ„Έν μ μ–΄μ£Όμ„Έμ”.'
      value: |
        ## μ–΄λ–¤ μ‘μ—…μΈκ°€μ”?
        > μ§„ν–‰ν•  μ‘μ—…μ— λ€ν•΄ κ°„λ‹¨ν•κ² μ„¤λ…ν•΄μ£Όμ„Έμ”.

        ## π”¨ μƒμ„Έ μ‘μ—… λ‚΄μ©
        - [ ] 
        - [ ] 

        ## π“„ μ°Έκ³  μ‚¬ν•­

        ## β° μμƒ μ†μ” κΈ°κ°„
    validations:
      required: true
