name: Feature Report
description: 기능 추가 이슈
title: "[FEAT]: "
labels: ["✨ 기능"]
body:
  - type: dropdown
    id: issueType
    attributes:
      label: 📥 Issue Type
      description: 'Jira 이슈 타입을 선택해주세요.'
      options:
        - Story
        - Task
        - Bug
      default: 0
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '📮 상세 내용 Description'
      description: '추가할 기능에 대해 설명해주세요.'
      value: |
        ## 어떤 기능인가요?
        > 추가할 기능에 대해 간단하게 설명해주세요.

        ## 🔨 상세 작업 내용
        - [ ] 
        - [ ] 

        ## 📄 참고 사항

        ## ⏰ 예상 소요 기간
    validations:
      required: true
