name: Github with JIRA 
description: '유레카 종합 프로젝트 Github & Jira 이슈 템플릿입니다.'
title: "[]: "
labels: []
body:
  - type: dropdown
    id: issueType
    attributes:
      label: 📥 Issue Type
      description: 'Jira 이슈 타입을 선택해주세요.'
      options:
        - Task
        - Story
        - 버그
      default: 0
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '📮 상세 내용 Description'
      description: '이슈에 대해서 자세히 설명해주세요'
      value: |
        -  개요
        > 이슈에 대해 간단하게 설명해주세요. 

        -  상세 작업 내용
        1. 작업 내용 1
        2. 작업 내용 2

        - 📄 참고 사항
         참고 자료나 스크린샷 등을 첨부해주세요.

        - ⏰ 예상 소요 기간

        - 어떤 버그인가요?
        > (버그라면) 어떤 버그인지 간단하게 설명해주세요


        - 어떤 상황에서 발생한 버그인가요?
        > 어떤 상황에서 / 무엇을 했을 때 / 어떻게 되어야 하는데 / 결과는 어떤지 서술해주세요


        - 예상 결과
        > 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

    validations:
      required: true
